baseURL = "https://jacksalici.com/"

title = "Giacomo Salici ~ Creative developer, digital craftsman."

[taxonomies]
category = "categories"
lang = "langs"
tags = "tags"
tool = "tools"

[permalinks]
'/' = '/:slug/'
'projects' = '/projects/:slug/'

[params]
author = "Jack Salici"
logoSvg = '''<svg  width="100%" height="100%" viewBox="0 0 942 1000" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/">
    <g transform="matrix(1,0,0,1,-383.556,-420.583)">
        <path d="M544.989,1122.5C579.959,1152.47 625.389,1170.58 675.017,1170.58C785.4,1170.58 875.017,1080.97 875.017,970.583L1125.02,970.583C1125.02,1218.94 923.379,1420.58 675.017,1420.58C563.875,1420.58 462.09,1380.2 383.556,1313.34L544.989,1122.5Z"/>
        <path d="M1324.98,420.583L1324.98,670.583C1214.6,670.583 1124.98,760.2 1124.98,870.583L874.983,870.583C874.983,622.221 1076.62,420.583 1324.98,420.583Z"/>
        <path d="M1008.84,420.583C921.088,482.377 852.184,569.178 812.535,670.583L540.994,670.583L540.994,420.583L1008.84,420.583Z"/>
    </g>
</svg>'''
#logoLabel = ""

DateFormat = "Jan 2006"
googleAnalytics = 'G-TCJ26JMX8T'

mainMenuSvg = '''
<svg class="icon w-7" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48"><path d="M110-558q-12.75 0-21.375-8.625T80-588v-10q0-109 105-175.5T480-840q190 0 295 66.5T880-598v10q0 12.75-8.625 21.375T850-558H110Zm32-60h676q-3-69-96.5-115.5T480-780q-148 0-242.5 46.5T142-618ZM80-416q0-8.878 7-17.439T105-447q23-8 45.564-23.5T216-486q54 0 71.5 22t58.5 22q41 0 60.5-22t73.5-22q54 0 73.5 22t60.5 22q41 0 58.5-22t71.5-22q43 0 65.5 15.5T855-447q11.184 5.25 18.092 13.125Q880-426 880-416q0 15.162-10.5 24.081Q859-383 846-386q-32-8-50.5-24t-51.515-16Q703-426 685.5-404T614-382q-54 0-73.5-22T480-426q-41 0-60.5 22T346-382q-54 0-71.5-22t-58.485-22Q183-426 164.5-410T114-386q-13 3-23.5-5.919T80-416Zm60 296q-24 0-42-18t-18-42v-68q0-24.75 17.625-42.375T140-308h680q24.75 0 42.375 17.625T880-248v68q0 24-18 42t-42 18H140Zm0-60h680v-68H140v68Zm2-438h676-676Zm-2 370h680-680Z"/></svg>
'''
mainMenuShowThemes = true
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true

taxonomyShown = ["Categories", "Langs", "Tools"]
text404 = "Looks like you're lost, but here's a link that takes you back to the <a href='/'>home</a>. If you are confident about your URL, it is likely that the content you were searching for has been moved to a new location. That's awkward... <br><br><img src='https://media.tenor.com/U_z21PJ3E28AAAAM/everybody-stay-calm-steve-carrell.gif'/><img src='https://media.tenor.com/CbhnRg0n7ksAAAAM/kermit-the-frog-looking-for-directions.gif' /><img src='https://media.tenor.com/khjOpd7-ungAAAAM/viggo-mortensen-journey.gif' /><img src='https://media.tenor.com/oTeBa4EVepMAAAAC/business-cat-working.gif' /><img src='https://media.tenor.com/oE7O8I0TvEwAAAAC/thats-all-folks.gif' />"
twemoji = true

[params.footer]
copy = 'Giacomo Salici. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" class="link">Some rights reserved.</a>'
credit = 'Made with 💖 and 🍕 on 🌍.'

[params.meta]
title = "Giacomo Salici ~ Creative developer, digital craftsman."
description = "I am a M.Sc. Computer Engineering student based in Modena, Italy. I like developing and designing random stuffs. Here are my latest projects."
keywords = ["jack salici", "Portfolio", "giacomo salici", "developer", "coding", "maker"]

[[params.social]]
featured = true
icon = "fa-brands fa-github"
name = "github"
url = "https://github.com/jacksalici"

[[params.social]]
featured = true
icon = "fa-brands fa-linkedin"
name = "linkedin"
url = "https://linkedin.com/in/jacksalici"

[[params.social]]
featured = true
icon = "fa-solid fa-envelope"
name = "email"
url = "mailto:hey@jacksalici.com"

[[params.social]]
featured = true
icon = "fa-brands fa-telegram"
name = "telegram"
url = "https://t.me/jacksalici"

[[params.social]]
featured = false
icon = "fa-brands fa-instagram"
name = "instagram"
url = "https://instagram.com/jacksalici"

[[params.social]]
featured = false
icon = "fa-brands fa-twitter"
name = "twitter"
url = "https://twitter.com/jacksalici"

[params.hero]
description = "My name is Giacomo Salici, I'm a developer and engineer based in Italy. Currently, I'm getting a M.Sc. degree in Computer Engineering, artificial intelligence curriculum."
title = "Digital craftsman, creative developer."

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'

[menu]
[[menu.main]] 
name = 'Homepage'
url = "/"
weight = 1

[[menu.main]]
 
name = 'Contact me'
url = "/contacts"
weight = 2

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy"
weight= 1 

[[menu.footer]]
name = "Website architecture"
url = "/projects/website/"
weight= 2

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"
